// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzxeIj94cIt5O5U9DS5OO_bTOLBKGxo8',
    appId: '1:105583620603:web:12be4b0e0471954dd95b5e',
    messagingSenderId: '105583620603',
    projectId: 'motorbikerentalapp-3b6ad',
    authDomain: 'motorbikerentalapp-3b6ad.firebaseapp.com',
    storageBucket: 'motorbikerentalapp-3b6ad.firebasestorage.app',
    measurementId: 'G-PRWE8T9149',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUGDxBY15eBJewaRWKzlwYu8RpXGS9kNM',
    appId: '1:105583620603:android:e448a54fb66de7a8d95b5e',
    messagingSenderId: '105583620603',
    projectId: 'motorbikerentalapp-3b6ad',
    storageBucket: 'motorbikerentalapp-3b6ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgg5_xsgT0FUbsC2Cgka5CJD5A9LdOOE',
    appId: '1:105583620603:ios:f3b1cf29a4ac5980d95b5e',
    messagingSenderId: '105583620603',
    projectId: 'motorbikerentalapp-3b6ad',
    storageBucket: 'motorbikerentalapp-3b6ad.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgg5_xsgT0FUbsC2Cgka5CJD5A9LdOOE',
    appId: '1:105583620603:ios:f3b1cf29a4ac5980d95b5e',
    messagingSenderId: '105583620603',
    projectId: 'motorbikerentalapp-3b6ad',
    storageBucket: 'motorbikerentalapp-3b6ad.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzxeIj94cIt5O5U9DS5OO_bTOLBKGxo8',
    appId: '1:105583620603:web:f3d03ac8d788f7e5d95b5e',
    messagingSenderId: '105583620603',
    projectId: 'motorbikerentalapp-3b6ad',
    authDomain: 'motorbikerentalapp-3b6ad.firebaseapp.com',
    storageBucket: 'motorbikerentalapp-3b6ad.firebasestorage.app',
    measurementId: 'G-ZPPR09BEMT',
  );
}
